org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Minecraft
# check these on https://fabricmc.net/develop and https://neoforged.net
minecraft_version=1.21.11
enabled_platforms=fabric,neoforge

# Mod
mod_version=1.1.0
maven_group=com.brendondugan.entangledchests
archives_base_name=entangledchests

# Dependencies
architectury_version=19.0.1
fabric_loader_version=0.19.3
fabric_api_version=0.141.5+1.21.11
neoforge_version=21.11.44
