modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "entangledchests"
version = "${version}"
displayName = "Entangled Chests"
authors = "Brendon Dugan"
logoFile = "assets/entangledchests/icon.png"
description = '''
Adds an entanglement crystal, an entangled chest, and an entangled bundle.
'''

[[dependencies.entangledchests]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,27)"
ordering = "NONE"
side = "BOTH"

[[dependencies.entangledchests]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,27)"
ordering = "NONE"
side = "BOTH"

[[dependencies.entangledchests]]
modId = "architectury"
type = "required"
versionRange = "[20.0.9,)"
ordering = "AFTER"
side = "BOTH"
